### ISSUE TITLE
Proof Read: Introduction

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/IntroToCSharpSite#120]

**Comment by promiseofwater** [comment]
Yes

**Comment by promiseofwater** [comment]
1. comma separating independent clauses
2. you had mentioned limiting I. "there is no one size fits all..."
3. comma after beginning
4. bold adventure mode
5. bold fast travel
6. bold captain coder





![Image](https://user-images.githubusercontent.com/59033964/186277339-88e66a9e-c240-4c13-ad71-d97e44b17fbc.png)

**Comment by jcollard** [comment]
Done. Thanks!

I think for this page, I'm okay with using "I do not believe". For this page, I want to feel like I'm talking with the reader and telling them about the book / my opinions.

**Comment by jcollard** [comment]
@promiseofwater 
Word count: 368
Link: https://docs.google.com/document/d/1y_g9qYXb-HQFppn1jZCelybiZmkkeEg57IQBIUE--4U/edit?usp=sharing
