### ISSUE TITLE
Proof Read: Creating a Console Project

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/IntroToCSharpSite#122]

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. bold
4. suggestion: text bubble or even animation of your avatar saying this
5. bold



![Image](https://user-images.githubusercontent.com/59033964/186524839-2bcd1a02-1f81-4c81-af6d-68b0c4701f25.png)

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. suggestion: have windows and mac tips assigned their own color. the word or bubble itself
4. bold




![Image](https://user-images.githubusercontent.com/59033964/186526738-049b8128-4774-4178-80a8-bba2b82f7f8d.png)

**Comment by promiseofwater** [comment]
1. both both and bubble used for terminal on this page
2. bold
3. bold/bubble
4. bold/bubble
5. bold/bubble
6. bold/bubble
7. bold/bubble
8. bold/bubble
9. bold/bubble
10.  hello bubble on most of page but "" here




![Image](https://user-images.githubusercontent.com/59033964/186527651-886f6fe8-2d57-4f47-9c4b-847b4626a811.png)

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. bold
4. in addition to what we talked about maybe add an exclamation clipart or something for tips to grab attention
5. bold




![Image](https://user-images.githubusercontent.com/59033964/186940644-df94fe4a-96b8-4023-9570-11aa7cabe1bc.png)

**Comment by promiseofwater** [comment]
1. bold 
2. remove you for better word flow
3. bold
4. bold
5. bold 
6. bold




![Image](https://user-images.githubusercontent.com/59033964/187233479-89d9584d-4eb9-4af6-9846-e6d3bea28abd.png)

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. bold
4. bold
5. bold
6. bold
7. bold
8. bold
9. bold



![Image](https://user-images.githubusercontent.com/59033964/187234267-31cb7913-4e4a-4392-8a1e-4219c53f0504.png)

**Comment by jcollard** [comment]
Revisions incorporated. Thanks!

I like the idea for a Mac / Windows / Linux color bubble. I will add that to the "Enhancements" task list.
