### ISSUE TITLE
Proof Read: ASCII Art

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/IntroToCSharpSite#123]

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. bold
4. bold
5. bold
6. bold
7. bold
8. bold
9. bold
10. bold




![Image](https://user-images.githubusercontent.com/59033964/187238590-d23ae4d6-dbe6-4fff-bb2c-e06efac76b0e.png)

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. bold
4. bold
5. bold
6. bold
7. bold
8. bold





![Image](https://user-images.githubusercontent.com/59033964/187239219-88267d72-b8b3-4a9e-8956-a54b88627801.png)

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. This is a really good visual aid. Use this often if it's not too much trouble to add.
4. bold
5. bold
6. bold
7. bold





![Image](https://user-images.githubusercontent.com/59033964/187240081-91076878-9acd-467d-8206-e2dfb098eebc.png)

**Comment by promiseofwater** [comment]
1. bold





![Image](https://user-images.githubusercontent.com/59033964/187240301-f09ab356-1309-4eea-b3c1-5bc2759feb41.png)

**Comment by jcollard** [comment]
Revisions incorporated.
