### ISSUE TITLE
Proof Read: User Input

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/IntroToCSharpSite#124]

**Comment by promiseofwater** [comment]
1. Previous instances of ASCII were all caps.
2. bold
3. caps
4. bold
5. bold
6. bold
7. bold





![Image](https://user-images.githubusercontent.com/59033964/187240949-46225af9-8805-459f-99e7-05daae7d4a2b.png)

**Comment by promiseofwater** [comment]
1. bold






![Image](https://user-images.githubusercontent.com/59033964/187241465-d408aa89-78dd-439e-810d-c07cbb3c8b1d.png)

**Comment by promiseofwater** [comment]
1. bold




![Image](https://user-images.githubusercontent.com/59033964/187242071-c0e55184-36ea-45aa-a374-f4423ebe05be.png)

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. bold





![Image](https://user-images.githubusercontent.com/59033964/187242711-f5b18b32-9152-4f83-96b2-08736e96b3f4.png)
