### ISSUE TITLE
Proof Read: Mad Takes

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/IntroToCSharpSite#125]

**Comment by promiseofwater** [comment]
1. I think you should bold this
2. bold
3. bold
4. this appears as bold text in the example below it
5. bold
6. bold
7. bold
8. bold





![Image](https://user-images.githubusercontent.com/59033964/187243734-c8232c9b-1e6f-4b0f-9980-b2b829dece4e.png)

**Comment by jcollard** [comment]
Revisions incorporated.
