### ISSUE TITLE
Proof Read: Variable Basics

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/IntroToCSharpSite#126]

**Comment by promiseofwater** [comment]
1. bold





![Image](https://user-images.githubusercontent.com/59033964/187244864-7d2fb2b5-26f6-4403-a5ec-d93ec0c0878b.png)

**Comment by promiseofwater** [comment]
1. bold





![Image](https://user-images.githubusercontent.com/59033964/187245145-1fde08dc-dbdd-4270-84f0-ef8bf58f5a51.png)

**Comment by promiseofwater** [comment]
no notes




![Image](https://user-images.githubusercontent.com/59033964/187245462-bda8f08f-8faf-4d92-88ed-2d77544e3b6f.png)

**Comment by jcollard** [comment]
Revisions incorporated.
