### ISSUE TITLE
Proof Read: Basic Data Types

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/IntroToCSharpSite#127]

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. bold





![Image](https://user-images.githubusercontent.com/59033964/187245917-8ada50d7-8c25-4782-b1d9-53ec55ef5941.png)

**Comment by promiseofwater** [comment]
1. bold
2. bold
3. Not sure if the s here should be bold since it appears below as well.
4. bold





![Image](https://user-images.githubusercontent.com/59033964/187246384-82313273-ddc3-418d-8ef7-db47b3a33e79.png)

**Comment by promiseofwater** [comment]
1. I think you should bold this
2. bold
3. bold
4. bold






![Image](https://user-images.githubusercontent.com/59033964/187247085-bb286dd7-61c5-43dc-868c-75a5e7a888a9.png)

**Comment by jcollard** [comment]
Revisions incorporated.
