### ISSUE TITLE
Extract Exploration components

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/IntroToCSharpSite#158]
Pull inline <Explore> components into an Exploration package.

**Comment by jcollard** [comment]
@cloudthepain I think this would be a good task for you.

**Comment by cloudthepain** [comment]
I don't know what this means :)

**Comment by jcollard** [comment]
@cloudthepain In the same way that we have a "Challenges" package (folder). It would be nice to have all of the "Explore" components moved into their own package. This will be useful for adding / tracking statistics:

<img width="631" alt="Screen Shot 2022-08-28 at 12 29 53 PM" src="https://user-images.githubusercontent.com/3529380/187091272-d188689c-acc9-410e-890d-e9114d3435d5.png">

**Comment by cloudthepain** [comment]
Ah, I see. I like that layout. I wonder if we could get something that would add their avatar's portrait to it?

**Comment by jcollard** [comment]
I would love to add in more user customization like an avatar portrait!

**Comment by cloudthepain** [comment]
Added with #164
